#!/bin/bash
# Compilation with latex

# Usage info
show_help() {
cat << EOF
    Usage: ${0##*/} [-bgpr] [-B BibTeX] [FILE.tex]...

    Run LaTeX for file FILE.tex and generates FILE.pdf

    -b          compiles File.bib to generate BibTeX file
    -B bibfile  compiles bibfile.bib to generate BibTeX file
    -g          run makeglossaries
    -r          delete .aux, .toc, .dvi, ...
    -p          compile with pdfLaTeX
EOF
 }

latexfile="${@: -1:1}"
l=${latexfile%.*}
echo "$latexfile"
echo "$l"
latexcomp=latex
dvipdfconv=true

OPTIND=1

while getopts ":bB:g" opt; do
    case $opt in
        b)
            bibcomp=true
            bibfile=$l
            ;;
        B)
            bibcomp=true
            bibfile=${OPTARG%.*}
            ;;
        g)
            makegloss=true
            ;;
        r)
            rm -f *.aux
            rm -f *.toc
            rm -f *.bbl
            rm -f *.blg
            rm -f *.dvi
            rm -f *.log
            rm -f *.ps
            rm -f *.out
            delated=1
            echo '\nRubish deleted...\n'
            ;;
        p)
            latexcomp=pdflatex
            dvipdfconv=false
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
        *)
            show_help >&2
            exit 1
            ;;
    esac
done

echo "Compiling $latexfile with $latexcomp"
#echo $latexfile
echo

# LaTeX first run
$latexcomp $l

######## Bibliography
if bibcomp; then
    echo
    echo '*****  Running BibTeX  *****'
    bibtex $bibfile
fi

if $makegloss; then
    echo
    echo '\n***** Running makeglossaries *****\n'
    makeglossaries $l
fi

echo
echo '*****  Running LaTeX again  *****'
$latexcomp $l
if [ "$delated" -eq 1 ]; then
    echo '*****  Running LaTeX again  *****'
    $latexcomp $l
fi

#### Converting DVI to PDF
if $dvipdfconv; then

    # Convert to PostScript
    echo
    echo '*****  Converting DVI to PS  *****'
    dvips -Ppdf -z -G0 -j0 $l.dvi -o

    # Convert to PDF
    echo
    echo '*****  Converting PS to PDF  *****'
    ps2pdf -sPAPERSIZE=a4 $l.ps
fi

# Deleting log,aux,dvi,out,snm,nav,toc
# rm *.log
# rm *.aux
# rm *.dvi
#
# rm *.snm
# rm *.nav
# rm *.toc
