#!/bin/bash
# Compilation with latex

# Usage info
show_help() {
cat << EOF
Usage: ${0##*/} [-bmgprh] [FILE.tex]

Run LaTeX for file FILE.tex and generates FILE.pdf

  -b   Compiles File.bib to generate BibTeX file
  -m   Compiles for multibib
  -g   Run makeglossaries
  -r   Delete .aux, .toc, .dvi, ...
  -p   Compile with pdfLaTeX
  -s   Use synctex option
  -n   Activate nonstop mode
  -h   Show this message
EOF
 }

if [ $# == 0 ]; then
    show_help >&2
    exit 1
fi

latexfile="${@: -1:1}"
l=${latexfile%.*}
flags=""
latexcomp="latex"
dvipdfconv=true
deltrash=false
makegloss=false
multbib=false

OPTIND=1

while getopts "bmgrpnsh" opt; do
    case $opt in
        b)
            bibcomp=true
            bibfile=$l
            ;;
        m)
             multbib=true
             ;;
        n)
            flags=$flags" -interaction=nonstopmode"
            ;;
        g)
            makegloss=true
            ;;
        r)
            deltrash=true
            ;;
        s)
            flags=$flags" -synctex=1"
            ;;
        p)
            latexcomp=pdflatex
            dvipdfconv=false
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
        h|*)
            show_help >&2
            exit 1
            ;;
    esac
done

echo "Compiling $latexfile with $latexcomp"
echo "Using flags: $flags"
echo

if $deltrash; then
    rm -f *.aux
    rm -f *.toc
    rm -f *.bbl
    rm -f *.blg
    rm -f *.brf
    rm -f *.fot
    rm -f *.dvi
    rm -f *.log
    rm -f *.lot
    rm -f *.lof
    rm -f *.syntex.gz
    rm -f *.ps
    rm -f *.out
    echo -e '\nRubish deleted...\n'
fi

# LaTeX first run
$latexcomp $flags $l

######## Bibliography
if $bibcomp; then
    echo
    echo -e '\n*****  Running BibTeX  *****\n'
    if $multbib; then
        for bfile in *.aux ; do
            bibtex `basename $bfile .aux`
        done
    else
        bibtex $bibfile
    fi
fi

if $makegloss; then
    echo
    echo -e '\n***** Running makeglossaries *****\n'
    makeglossaries $l
fi

echo
echo -e '\n*****  Running LaTeX again  *****\n'
$latexcomp $flags $l

    
if $deltrash; then
    echo -e '\n*****  Running LaTeX again  *****\n'
    $latexcomp $flags $l
fi

#### Converting DVI to PDF
if $dvipdfconv; then

    # Convert to PostScript
    echo
    echo -e '\n*****  Converting DVI to PS  *****\n'
    dvips -Ppdf -z -G0 -j0 $l.dvi -o

    # Convert to PDF
    echo
    echo -e '\n*****  Converting PS to PDF  *****\n'
    ps2pdf -sPAPERSIZE=a4 $l.ps
fi

# Deleting log,aux,dvi,out,snm,nav,toc
# rm *.log
# rm *.aux
# rm *.dvi
#
# rm *.snm
# rm *.nav
# rm *.toc
