#!/bin/bash
# Compilation with latex

# Usage info
show_help() {
cat << EOF
Usage: ${0##*/} [-bgprh] [-B BibTeX] [FILE.tex]

Run LaTeX for file FILE.tex and generates FILE.pdf

  -b            Compiles File.bib to generate BibTeX file
  -B <bibfile>  Compiles bibfile.bib to generate BibTeX file
  -g            Run makeglossaries
  -r            Delete .aux, .toc, .dvi, ...
  -h            Show this message
  -p            Compile with pdfLaTeX
  -s            Use synctex option
EOF
 }

if [ $# == 0 ]; then
    show_help >&2
    exit 1
fi

latexfile="${@: -1:1}"
l=${latexfile%.*}
latexcomp=latex
dvipdfconv=true
deltrash=false
makegloss=false
synctex=false

OPTIND=1

while getopts "brspgB:h" opt; do
    case $opt in
        b)
            bibcomp=true
            bibfile=$l
            ;;
        B)
            bibcomp=true
            bibfile=${OPTARG%.*}
            ;;
        g)
            makegloss=true
            ;;
        r)
            deltrash=true
            ;;
        s)
            synctex=true
            ;;
        p)
            latexcomp=pdflatex
            dvipdfconv=false
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
        h|*)
            show_help >&2
            exit 1
            ;;
    esac
done

echo "Compiling $latexfile with $latexcomp"
#echo $latexfile
echo

if $deltrash; then
    rm -f *.aux
    rm -f *.toc
    rm -f *.bbl
    rm -f *.blg
    rm -f *.dvi
    rm -f *.log
    rm -f *.ps
    rm -f *.out
    echo -e '\nRubish deleted...\n'
fi

# LaTeX first run
$latexcomp $l

######## Bibliography
if $bibcomp; then
    echo
    echo '*****  Running BibTeX  *****'
    bibtex $bibfile
fi

if $makegloss; then
    echo
    echo -e '\n***** Running makeglossaries *****\n'
    makeglossaries $l
fi

echo
echo '*****  Running LaTeX again  *****'
if $synctex; then
    $latexcomp -synctex=1 $l
else
    $latexcomp $l
fi
    
if $deltrash; then
    echo '*****  Running LaTeX again  *****'
    if $synctex; then
        $latexcomp -synctex=1 $l
    else
        $latexcomp $l
    fi
fi

#### Converting DVI to PDF
if $dvipdfconv; then

    # Convert to PostScript
    echo
    echo '*****  Converting DVI to PS  *****'
    dvips -Ppdf -z -G0 -j0 $l.dvi -o

    # Convert to PDF
    echo
    echo '*****  Converting PS to PDF  *****'
    ps2pdf -sPAPERSIZE=a4 $l.ps
fi

# Deleting log,aux,dvi,out,snm,nav,toc
# rm *.log
# rm *.aux
# rm *.dvi
#
# rm *.snm
# rm *.nav
# rm *.toc
